/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kripto;

import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import kripto.ListaSlika.Renderer;
import kripto.ListaSlika.Slika;

/**
 *
 * @author miroslav.mandic
 */
public class MainForm extends javax.swing.JFrame {
    
    public String getStelectedUSer(){
        return listUsers.getSelectedValue();
    }

    public void popuniKorisnike(User user){
        ArrayList<User>  korisnici = new ArrayList<User>(Arrays.asList(Main.KORISNICI));
        korisnici.remove(user);
        DefaultListModel model = new DefaultListModel();
        for (User u : korisnici)
        model.addElement(u.getUsername());
        listUsers.setModel(model);
    }
    
    public MainForm() {
        
        initComponents();
        popuniKorisnike(Main.KORISNIK);
        DefaultListModel model = new DefaultListModel();
        model.addElement(new Slika("Michael Carrick",
                new ImageIcon(new ImageIcon("src//slike//Desert.jpg").getImage()
                        .getScaledInstance(200, 150, java.awt.Image.SCALE_SMOOTH))));

        //RENDER IMAGES N TEXT
        listMessage.setCellRenderer(new Renderer());
        listMessage.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listMessage = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList<String>();
        btnPosaljiPoruku = new javax.swing.JButton();
        btnDekript = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Korisnici");

        listMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMessageMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listMessage);

        listUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUsersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listUsers);

        btnPosaljiPoruku.setText("Posalji Poruku");
        btnPosaljiPoruku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiPorukuActionPerformed(evt);
            }
        });

        btnDekript.setText("Dekriptuj");
        btnDekript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDekriptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnDekript)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnPosaljiPoruku)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addComponent(btnDekript))
                .addGap(18, 18, 18)
                .addComponent(btnPosaljiPoruku)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMessageMouseClicked
        Poruka poruka = new Poruka("KLIKNUO SAM", "KLIK", "INFO");
    }//GEN-LAST:event_listMessageMouseClicked

    private void listUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUsersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listUsersMouseClicked

    private void btnPosaljiPorukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiPorukuActionPerformed
        if (listUsers.getSelectedIndex() == -1) {
            new Poruka("Niste izabrali korisnika kome zelite da posaljete poruku", "Warrning", "Warrning");
        } else {
            PosaljiPoruku posaljiPoruku = new PosaljiPoruku(this);
            posaljiPoruku.setLocationRelativeTo(null);
            posaljiPoruku.setModal(true);
            posaljiPoruku.setVisible(true);
        }
        
    }//GEN-LAST:event_btnPosaljiPorukuActionPerformed

    private void btnDekriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDekriptActionPerformed
        try {
            Steganografija asd = new Steganografija();
            asd.dekodovanje("src//slike_kriptovane//rUiVP80mVg2PFT7kmUWs.png");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDekriptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainForm().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDekript;
    private javax.swing.JButton btnPosaljiPoruku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listMessage;
    private javax.swing.JList<String> listUsers;
    // End of variables declaration//GEN-END:variables
}
