/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kripto;

import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author miroslav.mandic
 */
public class PosaljiPoruku extends javax.swing.JDialog {

    /**
     * Creates new form PosaljiPoruku
     */
    public PosaljiPoruku(MainForm a) {
        initComponents();
        labelPrimalac.setText(a.getStelectedUSer());
        labelDatum.setText(new SimpleDateFormat("dd.MM.YYYY.  HH:mm:ss").format(new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUcitajSliku = new javax.swing.JButton();
        txtPutanjaDoSlike = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelPrimalac = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPoruka = new javax.swing.JTextArea();
        btnPosaljiPoruku = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelDatum = new javax.swing.JLabel();

        btnUcitajSliku.setText("Ucitaj sliku");
        btnUcitajSliku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcitajSlikuActionPerformed(evt);
            }
        });

        txtPutanjaDoSlike.setEditable(false);

        jLabel1.setText("Primalac poruke: ");

        labelPrimalac.setText("jLabel2");

        txtPoruka.setColumns(20);
        txtPoruka.setRows(5);
        txtPoruka.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtPoruka);

        btnPosaljiPoruku.setText("Posalji Poruku");
        btnPosaljiPoruku.setActionCommand("");
        btnPosaljiPoruku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiPorukuActionPerformed(evt);
            }
        });

        jLabel2.setText("Datum:");

        labelDatum.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(labelPrimalac)
                        .addGap(182, 182, 182)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDatum)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnUcitajSliku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPutanjaDoSlike, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(btnPosaljiPoruku)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelPrimalac)
                    .addComponent(jLabel2)
                    .addComponent(labelDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPutanjaDoSlike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUcitajSliku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnPosaljiPoruku)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUcitajSlikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcitajSlikuActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Images", "jpg", "png", "gif", "bmp"));
        fileChooser.setCurrentDirectory(new File ("src//slike"));
        StringBuilder sb = new StringBuilder();
        try {
            if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                File privatniKljuc = fileChooser.getSelectedFile();
                txtPutanjaDoSlike.setText(privatniKljuc.getAbsoluteFile().toString());

            } else {
                sb.append("No file was selected");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnUcitajSlikuActionPerformed

    private void btnPosaljiPorukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiPorukuActionPerformed
        if ("".equals(txtPutanjaDoSlike.getText()))
            new Poruka("Niste ucitali sliku!", "Info", "Info");
        else if ("".equals(txtPoruka.getText()))
            new Poruka("Unesite poruku!", "Info", "Info");
        else{
            Steganografija steg = new Steganografija(new File(txtPutanjaDoSlike.getText()));
            steg.kodovanje("Poruku poslao: " +Main.KORISNIK.getUsername() + 
                    "\nDatum slanja:\n" + labelDatum.getText() 
                    + "\nPoruka:\n" + txtPoruka.getText(), labelPrimalac.getText());
            new Poruka("Poruka je poslata.", "INFO", "INFO");
            this.dispose();
        }
    }//GEN-LAST:event_btnPosaljiPorukuActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPosaljiPoruku;
    private javax.swing.JButton btnUcitajSliku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDatum;
    private javax.swing.JLabel labelPrimalac;
    private javax.swing.JTextArea txtPoruka;
    private javax.swing.JTextField txtPutanjaDoSlike;
    // End of variables declaration//GEN-END:variables
}
